# Generated by Django 2.2.24 on 2022-05-13 08:53

from django.db import migrations
from django.db.models import F


def set_building_is_new(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.all().update(new_building=F('construction_year') >= 2015)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_building_is_new)
    ]
