# Generated by Django 2.2.24 on 2022-05-13 16:45
import phonenumbers

from django.db import migrations
from django.db.models import F


def get_correct_number(apps, schema_editor):
    def parse_number(raw_number):
        parsed_number = phonenumbers.parse(
                raw_number,
                'RU'
            )
        if phonenumbers.is_valid_number(parsed_number):
            return parsed_number

    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(
        owner_pure_phone=parse_number(
            F( 
                'owners_phonenumber'
                )
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(get_correct_number)
    ]
