# Generated by Django 2.2.24 on 2022-05-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220516_1328'),
    ]

    operations = [
    ]
