# Generated by Django 2.2.24 on 2022-05-16 12:05

from venv import create
from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name=flat.owner1,
            defaults={
                'phone': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220516_1503'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
