# Generated by Django 2.2.24 on 2022-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220516_1505'),
    ]

    operations = [
    ]
