# Generated by Django 2.2.24 on 2022-05-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220518_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
    ]
